### ISSUE TITLE
Pattern Scanner can be optimised

### ISSUE THREAD

**Issue by Yimura** [DaniTRDev/InternalMenuTemplate#12]
## Suggestions / Optimisations

 - [ ] `PatternBytes` is reallocated on the stack for each game address (this should never change)
 - [ ] `CurOpCode` is never used (?)
 - [ ] Restructuring the for loop allows you to save some lines although this doesn't need to be done

https://github.com/DaniTRDev/InternalMenuTemplate/blob/346ef645654ead74ecb18e265626a51eebd6bdaf/src/Threads/PatternScanner/PatternScanner.cpp#L105-L148

## My Optimisations
```cpp
bool pattern_batch::scan_pattern(pattern& pattern) const
{
	const auto pattern_bytes = pattern.get_pattern_bytes();
	for (std::uintptr_t i = m_module->get_base(); i < m_module->get_end(); i++)
	{
		const auto op_codes = reinterpret_cast<std::uint8_t*>(i);

		bool found = true;
		for (std::size_t op_idx = 0; op_idx < pattern_bytes.size() && found; op_idx++)
		{
			if (pattern_bytes[op_idx] == 0)
				continue;

			if (pattern_bytes[op_idx] != op_codes[op_idx])
				found = false;
		}

		if (found)
		{
			pattern.found(i);
			LOG(INFO) << "Found pattern '" << pattern.get_name() << "' -> " << m_module->get_name() << "+" HEX_TO_UPPER(i - m_module->get_base());

			return true;
		}
	}

	return false;
}
```

**Comment by DaniTRDev** [comment]
These issue has been taken care in the update I just pushed. Thank you.
